services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    ports:
      - 7700:7700
    volumes:
      - ./meilisearch/meili_data:/meili_data
    env_file: ./meilisearch/.env

  frontend:
    build: ./frontend
    depends_on:
      - meilisearch

  backend:
    build: ./backend
    depends_on:
      - meilisearch

  meilisearch_admin:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./meilisearch/admin/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./meilisearch/admin/public:/usr/share/nginx/html
    depends_on:
      - meilisearch

  proxy:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
